"use client";

import { useState, useRef } from "react";
import { Upload, Check, AlertTriangle } from "lucide-react";

export default function ModelImportPage() {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<Record<string, unknown> | null>(null);
  const [importing, setImporting] = useState(false);
  const [result, setResult] = useState<string | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  function handleFile(e: React.ChangeEvent<HTMLInputElement>) {
    const f = e.target.files?.[0];
    if (!f) return;
    setFile(f);
    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const data = JSON.parse(ev.target?.result as string) as Record<string, unknown>;
        setPreview(data);
      } catch {
        setPreview(null);
      }
    };
    reader.readAsText(f);
  }

  async function handleImport() {
    if (!file) return;
    setImporting(true);
    // Simulate import — in production, validate and store in Supabase
    await new Promise((r) => setTimeout(r, 1000));
    setResult("Model snapshot imported as DRAFT. Review and approve in the model review page.");
    setImporting(false);
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-semibold">Import Model Snapshot</h1>
        <p className="text-sm text-neutral-500 mt-1">Upload a model JSON file generated by the Python research engine</p>
      </div>

      <div className="card">
        <div
          className="border-2 border-dashed border-neutral-700 rounded-md p-8 text-center cursor-pointer hover:border-neutral-500 transition-colors"
          onClick={() => fileRef.current?.click()}
        >
          <Upload className="w-8 h-8 mx-auto mb-2 text-neutral-500" />
          <p className="text-sm text-neutral-400">
            {file ? file.name : "Click to select a model snapshot JSON file"}
          </p>
          <input ref={fileRef} type="file" accept=".json" className="hidden" onChange={handleFile} />
        </div>
      </div>

      {preview && (
        <div className="card space-y-3">
          <h2 className="text-sm font-semibold flex items-center gap-2"><Check className="w-4 h-4 text-green-400" /> Preview</h2>
          <div className="text-sm text-neutral-400 space-y-1">
            <p>Snapshot ID: {(preview.snapshot_id as string) || "—"}</p>
            <p>Effective Date: {(preview.effective_date as string) || "—"}</p>
            <p>Holdings: {Array.isArray(preview.holdings) ? preview.holdings.length : 0} stocks</p>
            <p>Model: {(preview.model_id as string) || "—"}</p>
          </div>
           <button onClick={handleImport} disabled={importing} className="btn btn-primary">
            {importing ? "Importing..." : "Import as Draft"}
          </button>
        </div>
      )}

      {result && (
        <div className="card border-green-500/30 bg-green-500/5">
          <p className="text-sm text-green-400 flex items-center gap-2"><Check className="w-4 h-4" /> {result}</p>
        </div>
      )}
    </div>
  );
}
