"""Write validated M1_B2_QUALITY_VETO_N30 output to Supabase."""
import json, os, csv, time
from supabase import create_client

url = os.environ["SUPABASE_URL"]
key = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
client = create_client(url, key)

with open("outputs/quarterly/m1_b2_quality_veto_targets.csv") as f:
    rows = list(csv.DictReader(f))

if len(rows) != 30:
    raise SystemExit(f"Expected 30 holdings, got {len(rows)}")

today = time.strftime("%Y-%m-%d")
ts = str(int(time.time()))
MODEL_ID = "M1_B2_QUALITY_VETO_N30"
TARGET = 1.0 / 30

# Upsert securities
sec_ids = {}
for r in rows:
    t = r["ticker"].strip().upper()
    existing = client.table("securities").select("id").eq("ticker", t).execute()
    if existing.data:
        sec_ids[t] = existing.data[0]["id"]
    else:
        created = client.table("securities").insert({
            "ticker": t, "sector": r.get("sector", ""), "industry": r.get("industry", ""), "is_active": True,
        }).execute()
        if created.data:
            sec_ids[t] = created.data[0]["id"]

# Model version
ver = client.table("model_versions").select("id").eq("model_id", MODEL_ID).execute()
mv_id = ver.data[0]["id"] if ver.data else client.table("model_versions").insert({
    "model_id": MODEL_ID, "version": today,
    "description": "Official M1_B2_QUALITY_VETO_N30 generated by GitHub Actions. Source: fresh_pilot_seed_v2.",
}).execute().data[0]["id"]

# Create snapshot
snap = client.table("model_snapshots").insert({
    "model_version_id": mv_id,
    "snapshot_id": f"gh-official-{ts}",
    "status": "DRAFT",
    "effective_date": today,
    "universe_screened": 2205, "eligible_count": 1070, "valid_score_count": 1034,
    "warnings": json.dumps({"generator": "github-actions-official", "run_id": os.environ.get("GITHUB_RUN_ID", "")}),
}).execute().data[0]

# Insert holdings
for i, r in enumerate(rows):
    sec = sec_ids.get(r["ticker"].strip().upper())
    if not sec: continue
    client.table("model_snapshot_holdings").insert({
        "snapshot_id": snap["id"], "security_id": sec, "rank": i + 1,
        "target_weight": TARGET,
        "b2_score": float(r.get("B2_score", 0)),
        "quality_percentile": float(r.get("Q_percentile", 0)),
        "quality_components_ok": int(r.get("Q_components_ok", 4)),
        "inclusion_reason": "Official M1_B2 Quality Veto. GitHub Actions.",
    }).execute()

print(f"Written: {len(rows)} holdings, snapshot_id={snap['snapshot_id']}")
