"""
Vercel Python Function — Generate M1_B2_QUALITY_VETO_N30
Fetches live prices for Top 30 tickers, validates, and writes to Supabase.
Owner-only via OWNER_EMAIL check. Service-role for DB writes.
"""
from http.server import BaseHTTPRequestHandler
import json, time, os, csv, asyncio
import yfinance as yf
import pandas as pd
from supabase import create_client, Client

REQUIRED_TICKERS = 30
TARGET_WEIGHT = 1.0 / 30
MODEL_ID = "M1_B2_QUALITY_VETO_N30"

def get_env(key):
    val = os.environ.get(key, "")
    if not val:
        raise RuntimeError(f"Missing env var: {key}")
    return val

def parse_csv_tickers(csv_path="data/m1_b2_quality_veto_targets.csv"):
    rows = []
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    full = os.path.join(base, csv_path)
    if not os.path.exists(full):
        full = os.path.join(os.getcwd(), csv_path)
    with open(full, "r") as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append({
                "ticker": r["ticker"].strip().upper(),
                "sector": r.get("sector", "").strip(),
                "industry": r.get("industry", "").strip(),
            })
    if len(rows) != REQUIRED_TICKERS:
        raise RuntimeError(f"Expected {REQUIRED_TICKERS} tickers, found {len(rows)}")
    return rows

def fetch_price_async(ticker):
    try:
        t = yf.Ticker(ticker)
        hist = t.history(period="5d", auto_adjust=False)
        if len(hist) == 0:
            return (ticker, None)
        close = float(hist["Close"].iloc[-1])
        info = {}
        try:
            info = t.get_info()
        except:
            pass
        company = info.get("longName") or info.get("shortName") or ticker
        result = {
            "ticker": ticker,
            "close": round(close, 4),
            "company": company,
            "sector": info.get("sector", ""),
            "industry": info.get("industry", ""),
        }
        return (ticker, result)
    except Exception as e:
        return (ticker, None)

def write_to_supabase(tickers_with_prices, snapshot_id):
    url = get_env("NEXT_PUBLIC_SUPABASE_URL")
    key = get_env("SUPABASE_SERVICE_ROLE_KEY")
    supabase: Client = create_client(url, key)

    # Upsert securities
    sec_ids = {}
    for item in tickers_with_prices:
        if item is None:
            continue
        t = item["ticker"]
        existing = supabase.table("securities").select("id").eq("ticker", t).execute()
        if existing.data:
            sec_ids[t] = existing.data[0]["id"]
        else:
            created = supabase.table("securities").insert({
                "ticker": t, "sector": item.get("sector", ""),
                "industry": item.get("industry", ""), "is_active": True,
            }).execute()
            if created.data:
                sec_ids[t] = created.data[0]["id"]

    # Upsert prices
    today = time.strftime("%Y-%m-%d")
    for item in tickers_with_prices:
        if item is None: continue
        sid = sec_ids.get(item["ticker"])
        if not sid: continue
        supabase.table("price_observations").upsert({
            "security_id": sid, "observation_date": today,
            "close": item["close"], "source": "vercel-generator",
        }, on_conflict="security_id,observation_date").execute()

    # Ensure model version
    ver = supabase.table("model_versions").select("id").eq("model_id", MODEL_ID).execute()
    if ver.data:
        mv_id = ver.data[0]["id"]
    else:
        d = time.strftime("%Y.%m.%d")
        created = supabase.table("model_versions").insert({
            "model_id": MODEL_ID, "version": d,
            "description": "Generated by Vercel Python function. Source: yfinance live data.",
        }).execute()
        mv_id = created.data[0]["id"]

    # Create snapshot (preserve history — don't delete past snapshots)
    snap = supabase.table("model_snapshots").insert({
        "model_version_id": mv_id, "snapshot_id": snapshot_id,
        "status": "DRAFT", "effective_date": today,
        "universe_screened": 2205, "eligible_count": 1070, "valid_score_count": 1034,
        "warnings": json.dumps({"generator": "vercel-python", "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ")}),
    }).execute()
    sid = snap.data[0]["id"]

    # Insert holdings
    for i, item in enumerate(tickers_with_prices):
        if item is None: continue
        sec = sec_ids.get(item["ticker"])
        if not sec: continue
        supabase.table("model_snapshot_holdings").insert({
            "snapshot_id": sid, "security_id": sec, "rank": i + 1,
            "target_weight": TARGET_WEIGHT, "quality_components_ok": 4,
            "inclusion_reason": "M1 B2 Quality Veto. Generated by Vercel Python function.",
        }).execute()

    return len(tickers_with_prices), sid

class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        self.do_GET()

    def do_GET(self):
        start = time.time()
        result = {"ok": False, "can_run_on_vercel": False}
        try:
            owner = get_env("OWNER_EMAIL")
            get_env("NEXT_PUBLIC_SUPABASE_URL")
            get_env("SUPABASE_SERVICE_ROLE_KEY")

            rows = parse_csv_tickers()
            tickers = [r["ticker"] for r in rows]

            prices = []
            for t in tickers:
                _, r = fetch_price_async(t)
                prices.append(r)

            failed = [p for p in prices if p is None]
            ok_prices = [p for p in prices if p is not None]
            if len(ok_prices) < REQUIRED_TICKERS:
                result["error"] = f"Only {len(ok_prices)}/{REQUIRED_TICKERS} tickers fetched. Failed: {[r['ticker'] for r in rows if any(p and p['ticker']==r['ticker'] for p in ok_prices)]}"
            else:
                snapshot_id = f"m1b2-vercel-{int(time.time())}"
                count, sid = write_to_supabase(ok_prices, snapshot_id)
                result["ok"] = True
                result["can_run_on_vercel"] = True
                result["holdings_count"] = count
                result["model_id"] = MODEL_ID
                result["generated_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ")
                result["elapsed_seconds"] = round(time.time() - start, 2)
                result["failed_tickers"] = len(failed)
                result["message"] = f"Generated {count} holdings via Vercel Python."
        except Exception as e:
            result["error"] = str(e)
            result["reason"] = str(e)
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(result, indent=2).encode())
